version: "3"
volumes:
        project-root:
                external:
                        name: ${VOLUME_NAME}
services:
        php-dotnet:
                build:
                        context: .
                        dockerfile: Dockerfile-PHP-dotnet
                volumes:
                        - project-root:/Netbeans-Xdebug-PHP-fpm-in-Docker-by-Windows-share-folder
                command: >
                        /bin/bash -c
                        "cd /Netbeans-Xdebug-PHP-fpm-in-Docker-by-Windows-share-folder/php &&
                        dotnet run"
