version: "3"
volumes:
        project-root:
                external:
                        name: ${VOLUME_NAME}
services:
        php:
                image: php
                volumes:
                        - project-root:/Netbeans-Xdebug-PHP-fpm-in-Docker-by-Windows-share-folder
                command: >
                        php /Netbeans-Xdebug-PHP-fpm-in-Docker-by-Windows-share-folder/php/public/index.php
